name: Build and publish docker containers

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
      tags:
        type: string
        default: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha
      build-args:
        type: string
      dockerfile:
        type: string
        default: Dockerfile
      context:
        type: string
        default: "{{defaultContext}}"
      push:
        type: boolean
        default: true
      registry-dockerhub:
        type: boolean
        default: true
      registry-github:
        type: boolean
        default: true
      registry-readme:
        type: string
        default: README.md
      runs-on:
        type: string
        default: ubuntu-latest
      platforms:
        type: string
        default: linux/amd64
    outputs:
      digest:
        description: "Digest of docker image"
        value: ${{ jobs.build_publish_docker.outputs.digest }}
      primary-image:
        description: "Primary full name of pushed docker image"
        value: ${{ jobs.build_publish_docker.outputs.primary-image }}

jobs:
  build_publish_docker:
    runs-on: ${{ inputs.runs-on }}

    permissions:
      packages: write
      contents: read

    outputs:
      digest: ${{ steps.dockerBuild.outputs.digest }}
      primary-image: ${{ steps.get-primary-image.outputs.primary-image }}

    steps:
      - name: Log in to Docker Hub
        if: inputs.registry-dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to the Github registry
        if: inputs.registry-github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set image names
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "image-names<<$EOF" >> "$GITHUB_ENV"
          if ${{ inputs.registry-dockerhub }} ; then
            echo "${{ inputs.image-name }}" >> "$GITHUB_ENV"
          fi
          if ${{ inputs.registry-github }} ; then
            echo "ghcr.io/${{ inputs.image-name }}" >> "$GITHUB_ENV"
          fi
          echo "$EOF" >> "$GITHUB_ENV"
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.image-names }}
          # generate Docker tags based on the following events/attributes
          tags: |
            ${{ inputs.tags }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      # Needed for cache layers on github registry
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker images
        id: dockerBuild
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ inputs.platforms }}
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max	
 
      # publish README on docker hub
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Docker Hub Description
        if: inputs.registry-dockerhub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ inputs.image-name }}
          readme-filepath: ${{ inputs.registry-readme }}

      - name: Selecting primary image from
        run: echo "${{ fromJSON(steps.dockerBuild.outputs.metadata)['image.name'] }}"
        
      - name: Set output image
        id: get-primary-image
        run: echo "primary-image=$( cut -d ',' -f 1 <<< "${{ fromJSON(steps.dockerBuild.outputs.metadata)['image.name'] }}" )" >> "$GITHUB_OUTPUT"	
