name: Publish Docker images

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  # shortest build, all repo defaults
  build-ai-dedicated-workflows:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    secrets: inherit
    
  build-hello-universe:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      registry-repo-name: hello-universe
    secrets: inherit
    
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug outputs
        run: echo "${{ needs.build-hello-universe.outputs }}"
      - name: debug digest
        run: echo "${{ needs.build-hello-universe.outputs.digest }}"
      - name: debug primary image
        run: echo "${{ needs.build-hello-universe.outputs.primary-image }}"
    needs: build-hello-universe
        
  build-hello-outerspace:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      registry-repo-name: hello-outerspace
      dockerfile: Dockerfile.dependent
      build-args: |
        FROM_IMAGE=${{ needs.build-hello-universe.outputs.primary-image }}
    secrets: inherit
    needs: build-hello-universe
