name: Jupyter Tests that should fail

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  test-service-batch-fail:
    uses: ./.github/workflows/operation-test-with-jupyter.yml
    with:
      image: nginx:mainline
      port-mapping: "8080:80" 
      additional-python-dependencies: requests
      notebook: tests
